### ISSUE TITLE
incompatibility between polyglossia  and tikz-cd

### ISSUE THREAD

**Issue by mennucc** [astoff/tikz-cd#13]
Dear [Augusto Stoffel](https://www.ctan.org/author/stoffel)

there is a weird incompatibility between polyglossia  and tikz-cd  : the following snippet fails

```
\documentclass{article}
\usepackage{tikz-cd}
\usepackage{polyglossia}
\setdefaultlanguage{italian}
\begin{document}
  \begin{tikzcd}%
    { A }  \arrow [r,  "{f}"]   \arrow [d,  "{\pi }"] & B \\ 
    { \frac  A \sim } \arrow [ur,   "{\tilde  f}"'] &
  \end{tikzcd}  
\end{document}
```
but if you set it to _\setdefaultlanguage{english}_ it will work

I tried it with both `lualatex` and `xelatex` ; I am using Ubuntu 21.04 , texlive 2020.20210202-3

thanks
a.

**Comment by astoff** [comment]
What happens if you add `\usetikzlibrary{babel}` to the preamble?

**Comment by mennucc** [comment]
👍 it fixes the problem. This compiles fine, and the `table of contents` has the italian title `Indice`, as expected. 

```
\documentclass [a4paper] {article}
\usepackage{polyglossia}
\setdefaultlanguage{italian}
\setotherlanguages{english}
\usepackage{tikz-cd}
\usetikzlibrary{babel}
\begin{document}
\begin{tikzcd}
A \arrow[rd] \arrow[r, "\phi"] & B \\ & C
\end{tikzcd}
\tableofcontents
\end{document}
```

Moreover, it works fine regardless of the order of packages in the preamble , so it is robust. 

Thanks a lot.

You may want to mention this in the documentation, and/or to activate `\usetikzlibrary{babel}` automatically inside `XeLaTeX` or `LuaLaTeX`

a.

**Comment by astoff** [comment]
> You may want to mention this in the documentation

It is already mentioned :-). But I will add the remark that polyglossia also has this issue.
