### ISSUE TITLE
 LMTX incompatbility: don't use fixed strings for \meaning

### ISSUE THREAD

**Issue by leahneukirchen** [astoff/tikz-cd#15]
This is the same issue as https://github.com/pgf-tikz/pgf/issues/1193.

Adjusting https://github.com/astoff/tikz-cd/blob/54f526719f8c404555af699f9253932d543e50ff/tikzlibrarycd.code.tex#L155 is needed.

**Comment by astoff** [comment]
All right, I made the change you suggest. I tested it in texlive, let me know if this works in LMTX.

Is it meaningful to make a CTAN release — I mean, does LMTX fetch packages from there?

**Comment by leahneukirchen** [comment]
Thanks for the quick fix. LMTX doesn't fetch external packages at all, ConTeXt has a modules system for that. I'll contact the TikZ module maintainer to update it.

**Comment by jonsterling** [comment]
@astoff @leahneukirchen I've just installed TeX Live 2024, and it seems like this update hasn't taken effect. I am wondering if this can be released?
