### ISSUE TITLE
Incompatibility with `polyglossia` when language is German

### ISSUE THREAD

**Issue by NaoPross** [astoff/tikz-cd#18]
Hi, I have no idea on why, but this does not compile if the language is set to german.

```tex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{german}

\usepackage{tikz}
\usetikzlibrary{quotes, cd}

\begin{document}
  \begin{tikzcd}
    \mathcal{C} \arrow[r, bend left=50, "1"] & \mathcal{C}
  \end{tikzcd}
\end{document}
```
With the following error.
```
...
! Package pgfkeys Error: I do not know the key '/tikz/"1"' and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help
...
l.13 I think the culprit is a tikzcd arrow in cell 1-1.
\errmessage ...currentrow -\tikzcd@currentcolumn }

l.15   \end{tikzcd}

? No pages of output.
Transcript written on breaks.log.
```

I have a found a relevant stackexchange discussion with a fix
https://tex.stackexchange.com/questions/557666/incompatibility-between-tikz-cd-and-german-language-under-polyglossia

But since it was not exactly easy to debug, I think it is worth mentioning this incompatiblity somewhere in the documentation.

**Comment by astoff** [comment]
This was added to the documentation in 54f526719f8c404555af699f9253932d543e50ff. I just hasn't been released yet...
