### ISSUE TITLE
How to change style of nodes

### ISSUE THREAD

**Issue by wstomv** [astoff/tikz-cd#6]
it would be nice to mention in the `tikz-cd` manual how to change the style of nodes within a `tikzcd` environment.

I am not a TikZ user, and had a hard time finding out: reading about the interals of `tikz-cd`, and searching (mostly in vain) on the web. In the end, it turned out to be so easy (but not something one would easily guess).

> Prepend `|[...style info...]|` to the node you want to style.

**Comment by casouri** [comment]
Thanks! This very helpful.
